// Database Referensi Kodefikasi PDAM Batulanteh

const DB = {
    komponen: { "01": "SUMBAWA" },
    direktorat: { "01": "UMUM", "02": "TEKHNIK" },
    bidang: {
        "01": "KANTOR PUSAT", "02": "CABANG SUMBAWA", "03": "CABANG EMPANG",
        "04": "CABANG PLAMPANG", "05": "CABANG UTAN", "06": "CABANG ALAS", "07": "CABANG ALAS BARAT"
    },
    lokasi: {
        "01": "GEDUNG KANTOR PUSAT", "02": "GUDANG", "03": "INTAKE SEMONGKAT", "04": "WTP BATULANTEH",
        "05": "WTP UNTER IWES", "06": "KANTOR CABANG SUMBAWA", "07": "UNIT PELAYANAN MOYO HILIR",
        "08": "UNIT PELAYANAN MOYO UTARA", "09": "UNIT PELAYANAN BADAS", "10": "RUMAH POMPA SUMER PAYUNG",
        "11": "SB BRANG BIJI", "12": "SB PURI HARMONY", "13": "SB SAMOTA RESIDENCE",
        "14": "RUMAH DINAS BRANG BARA", "15": "KANTOR CABANG EMPANG", "16": "INTAKE BUAS",
        "17": "KANTOR CABANG PLAMPANG", "18": "KANTOR PELAYANAN LAPE", "19": "KANTOR CABANG UTAN",
        "20": "UNIT PELAYANAN PERNANG", "21": "WTP BERINGIN SILA", "22": "KANTOR CABANG ALAS",
        "23": "WTP MARENTEH", "24": "KANTOR CABANG ALAS BARAT", "25": "SB USAR MAPIN", "26": "INTAKE RIMAS"
    },
    golongan: {
        "01": "TANAH", "02": "PERALATAN DAN MESIN", "03": "GEDUNG DAN BANGUNAN",
        "04": "JALAN, JEMBATAN, IRIGASI, INSTALASI, DAN JARINGAN", "05": "ASET TETAP LAINNYA",
        "06": "KONSTRUKSI DALAM PENGERJAAN", "07": "ASET TAK BERWUJUD"
    },
    kelompok: {
        "01": "TANAH", "02": "HAK ATAS TANAH", "03": "KENDARAAN", "04": "PERALATAN ALAT KERJA",
        "05": "POMPA", "06": "MEUBEL", "07": "PERALATAN KANTOR/ ELEKTRONIK", "08": "JALAN DAN JEMBATAN",
        "09": "BANGUNAN AIR", "10": "INSTALASI", "11": "JARINGAN", "12": "BAHAN PERPUSTAKAAN",
        "13": "ASET TETAP DALAM RENOVASI", "14": "KONSTRUKSI DALAM PENGERJAAN", "15": "APLIKASI", "16": "GOOD WILL"
    },
    sub_kelompok: {
        "01": "TANAH", "02": "HAK ATAS TANAH", "03": "MOBIL", "04": "SEPEDA MOTOR", "05": "GENSET",
        "06": "MESIN LAS", "07": "KOMPRESOR", "08": "SENAI", "09": "MANOMETER", "10": "ARCO",
        "11": "GPS", "12": "PERALATAN K3", "13": "MESIN POMPA", "14": "POMPA SUBMERSIBLE",
        "15": "POMPA DOSING", "16": "MEJA", "17": "KURSI", "18": "LEMARI", "19": "TV",
        "20": "KOMPUTER", "21": "PRINTER", "22": "UPS", "23": "KULKAS", "24": "SOUND SYSTEM",
        "25": "PERANTI DAPUR", "26": "CCTV", "27": "AC", "28": "KIPAS ANGIN"
    },
    sub_sub_kelompok: {
        "01": "TANAH", "02": "HAK ATAS TANAH", "03": "TANGKI", "04": "MOBIL STATION", "05": "OPEN CUP",
        "06": "RODA TIGA", "07": "RODA DUA", "08": "GENSET BESAR", "09": "GENSET PORTABLE",
        "10": "MESIN LAS HDPE", "11": "MESIN LAS LISTRIK", "12": "KOMPRESOR", "13": "SENAI LISTRIK",
        "14": "MANOMETER", "15": "ARCO", "16": "GPS", "17": "ROMPI KERJA", "18": "SAFETY SHOES",
        "19": "HELM", "20": "KERUCUT RAIL", "21": "RANTAI PEMBATAS", "22": "MESIN POMPA",
        "23": "POMPA SUBMERSIBLE", "24": "POMPA DOSING", "25": "MEJA RAPAT", "26": "MEJA KERJA 1 BIRO",
        "27": "MEJA KERJA 1/2 BIRO", "28": "MEJA PINGPONG", "29": "MEJA TAMU", "30": "MEJA KASIR",
        "31": "KURSI DIREKTUR", "32": "KURSI TAMU", "33": "KURSI KERJA", "34": "KURSI TUNGGU",
        "35": "LEMARI KAYU", "36": "LEMARI BESI", "37": "LEMARI ARSIP", "38": "BRANKAS",
        "39": "TV", "40": "BRACKET TV", "41": "MONITOR", "42": "KOMPUTER AIO", "43": "LAPTOP",
        "44": "PRINTER", "45": "PRINTER SCANNER", "46": "PRINTER THERMAL", "47": "PRINTER BARCODE",
        "48": "UPS", "49": "KULKAS 1 PINTU", "50": "KULKAS 2 PINTU", "51": "SPEAKER ACTIVE",
        "52": "MICROPHONE", "53": "MAGICCOM", "54": "PERALATAN DAPUR", "55": "CCTV",
        "56": "NVR 32 CHANEL", "57": "KAMERA 2MP COLOURVUE", "58": "SWITCH POE 16 PORT UNMANAGEABLE",
        "59": "MODEM GSM", "60": "WALLMOUNT RAK", "61": "BOX PANEL", "62": "CONVERTER FO 2 UTP",
        "63": "MIKROTIK", "64": "SWITCH MANAGEABLE 16 PORT", "65": "ACCESS POINT", "66": "AC GANTUNG",
        "67": "AC STANDING", "68": "KIPAS ANGIN GANTUNG", "69": "KIPAS ANGIN STANDING",
        "70": "DISPENSER", "71": "CPU", "72": "SWITCH POE 8 PORT UNMANAGEABLE", "73": "LEMARI PLASTIK"
    }
};
